--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/InventoryRollbacks
build-by-default: true
projects:
  InventoryRollbacks:
    path: ""
    icon: "icon.png"
    excludeDirs:
      - .github
      - build
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
      - phpstan.neon.dist
      - phpstan-baseline.php
      - .php-cs-fixer.php
    libs:
      - src: muqsit/invmenu/InvMenu
        version: ^4.6.0
      - src: jasonw4331/libCustomPack/libCustomPack
        version: ^1.0.1
      - src: https://poggit.pmmp.io/r/218648/Commando_pr-20.phar
...
