--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonwynn10/InventoryRollbacks
build-by-default: true
projects:
  InventoryRollbacks:
    path: ""
    icon: "icon.png"
    lint: false
    excludeDirs:
      - tests
      - .github
      - build
      - phpstan
    excludeFiles:
      - .gitignore
      - CONTRIBUTING.md
      - SECURITY.md
    libs:
      - src: muqsit/invmenu/InvMenu
        version: ^4.5.0
      - src: jasonwynn10/libCustomPack/libCustomPack
        version: ^0.1.1
      - src: CortexPE/Commando/Commando
        version: ^3.0.0
...
