name: InventoryRollbacks
main: jasonwynn10\InventoryRollbacks\Main
src-namespace-prefix: jasonwynn10\InventoryRollbacks
version: 1.0.0
api: 4.0.0
description: "A plugin which allows players to politely ask for a teleport"
author: "jasonwynn10"

permissions:
  inventoryrollback.command:
    description: "Allows the user to run the inventory rollback command"
    default: op