name: InventoryRollbacks
main: jasonw4331\InventoryRollbacks\Main
src-namespace-prefix: jasonw4331\InventoryRollbacks
version: 1.0.0
api: 5.0.0
description: "A plugin which allows players to politely ask for a teleport"
author: "jasonw4331"

permissions:
  inventoryrollback.command:
    description: "Allows the user to run the inventory rollback command"
    default: op